PierreAuthId/Models/Flavors.cs
using System.Collections.Generic;

namespace PierreAuthId.Models
{
  public class Flavors
  {
    public Flavors()
    {
      this.JoinEntities = new HashSet<TreatsFlavors>();
    }

    public int FlavorsId { get; set; }
    public string Type { get; set; }
    public virtual ApplicationUser User { get; set; }
    public virtual ICollection<TreatsFlavors> JoinEntities { get;}
  }
}

PierreAuthId/Controllers/FlavorsController.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc;
using PierreAuthId.Models;
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using System.Threading.Tasks;
using System.Security.Claims;

namespace PierreAuthId.Controllers
{
  [Authorize]
  public class FlavorsController : Controller
  {
    private readonly PierreAuthIdContext _db;
    private readonly UserManager<ApplicationUser> _userManager;

    public FlavorsController(UserManager<ApplicationUser> userManager, PierreAuthIdContext db)
    {
      _userManager = userManager;
      _db = db;
    }

    public async Task<ActionResult> Index()
    {
      var userId = this.User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
      var currentUser = await _userManager.FindByIdAsync(userId);
      var userFlavors = _db.Flavors.Where(entry => entry.User.Id == currentUser.Id).ToList();
      return View(userFlavors);
    }

    public ActionResult Create()
    {
      ViewBag.TreatsId = new SelectList(_db.Treats, "TreatsId", "Name");
      return View();
    }

    [HttpPost]
    public async Task<ActionResult> Create(Flavors Flavors, int TreatsId)
    {
      var userId = this.User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
      var currentUser = await _userManager.FindByIdAsync(userId);
      Flavors.User = currentUser;
      _db.Flavors.Add(Flavors);
      _db.SaveChanges();
      if (TreatsId != 0)
      {
          _db.TreatsFlavors.Add(new TreatsFlavors() { TreatsId = TreatsId, FlavorsId = Flavors.FlavorsId });
      }
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Details(int id)
    {
      var thisFlavors = _db.Flavors
          .Include(Flavors => Flavors.JoinEntities)
          .ThenInclude(join => join.Treats)
          .FirstOrDefault(Flavors => Flavors.FlavorsId == id);
      return View(thisFlavors);
    }

    public ActionResult Edit(int id)
    {
      var thisFlavors = _db.Flavors.FirstOrDefault(Flavors => Flavors.FlavorsId == id);
      ViewBag.TreatsId = new SelectList(_db.Treats, "TreatsId", "Name");
      return View(thisFlavors);
    }

    [HttpPost]
    public ActionResult Edit(Flavors Flavors, int TreatsId)
    {
      if (TreatsId != 0)
      {
        _db.TreatsFlavors.Add(new TreatsFlavors() { TreatsId = TreatsId, FlavorsId = Flavors.FlavorsId });
      }
      _db.Entry(Flavors).State = EntityState.Modified;
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult AddTreat(int id)
    {
      var thisFlavors = _db.Flavors.FirstOrDefault(Flavors => Flavors.FlavorsId == id);
      ViewBag.TreatsId = new SelectList(_db.Treats, "TreatsId", "Name");
      return View(thisFlavors);
    }

    [HttpPost]
    public ActionResult AddTreat(Flavors flavors, int treatsId)
    {
      if (treatsId != 0)
      {
      _db.TreatsFlavors.Add(new TreatsFlavors() { TreatsId = treatsId, FlavorsId = flavors.FlavorsId });
      }
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Delete(int id)
    {
      var thisFlavors = _db.Flavors.FirstOrDefault(Flavors => Flavors.FlavorsId == id);
      return View(thisFlavors);
    }

    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(int id)
    {
      var thisFlavors = _db.Flavors.FirstOrDefault(Flavors => Flavors.FlavorsId == id);
      _db.Flavors.Remove(thisFlavors);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    [HttpPost]
    public ActionResult DeleteTreats(int joinId)
    {
      var joinEntry = _db.TreatsFlavors.FirstOrDefault(entry => entry.TreatsFlavorsId == joinId);
      _db.TreatsFlavors.Remove(joinEntry);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
  }
}

PierreAuthId/Views/Flavors/AddTreat.cshtml
@{
  Layout = "_Layout";
}

@model PierreAuthId.Models.Flavors

<h2>Add a treat</h2>

<h4>Add a treat for this flavor, @Html.DisplayFor(model => model.Type)</h4>

@using (Html.BeginForm())
{
  @Html.HiddenFor(model => model.FlavorsId)

  @Html.Label("Select Treat")
  @Html.DropDownList("TreatsId")

  <input type="submit" value="Save" />
}

<br>
<p>@Html.ActionLink("Back to list", "Index")</p>

PierreAuthId/Views/Flavors/AddTreats.cshtml
@{
  Layout = "_Layout";
}

@model PierreAuthId.Models.Flavors

<h2>Add a treat</h2>

<h4>Add a treat for this flavor, @Html.DisplayFor(model => model.Type)</h4>

@using (Html.BeginForm())
{
  @Html.HiddenFor(model => model.FlavorsId)

  @Html.Label("Select Treat")
  @Html.DropDownList("TreatsId")

  <input type="submit" value="Save" />
}

<br>
<p>@Html.ActionLink("Back to list", "Index")</p>

PierreAuthId/Views/Flavors/Create.cshtml
@{
  Layout = "_Layout";
}

@model PierreAuthId.Models.Flavors

<h4>Add a new Flavor</h4>

@using (Html.BeginForm())
{
  @Html.LabelFor(model => model.Type)
  @Html.TextBoxFor(model => model.Type)

  <input type="submit" value="Add new item" class="btn btn-default" />
}
<p>@Html.ActionLink("Show all items", "Index")</p>

PierreAuthId/Views/Flavors/Delete.cshtml
@{
  Layout = "_Layout";
}

@model PierreAuthId.Models.Flavors

<h2>Are you sure you want to delete this?</h2>

@Html.DisplayNameFor(model => model.Type): @Html.DisplayFor(model => model.Type)
@using (Html.BeginForm())
{
  <input type="submit" value="Delete" />
}
@Html.ActionLink("Back to List", "Index")

PierreAuthId/Views/Flavors/Details.cshtml
@{
  Layout = "_Layout";
}

@model PierreAuthId.Models.Flavors

<h2>Flavor Details</h2>
<hr />
<h3>@Html.DisplayNameFor(model => model.Type): @Html.DisplayFor(model => model.Type)</h3>

@if(@Model.JoinEntities.Count == 0)
{
  <p>This flavor does not belong to any treats</p>
}
else
{
  <h4>Treats this flavor belongs to:</h4>
  <ul>
  @foreach(var join in Model.JoinEntities)
  {
    <li>@join.Treats.Name</li>
    @using (Html.BeginForm("DeleteTreats", "Flavors"))
    {
      @Html.Hidden("joinId", @join.TreatsFlavorsId)
      <input type="submit" value="Delete"/>
    }
  }
  </ul>
}
<br>
<p>@Html.ActionLink("Add a Treat", "AddTreat", new { id = Model.FlavorsId })</p><br>
<p>@Html.ActionLink("Back to list", "Index")</p><br>
<p>@Html.ActionLink("Edit Flavor", "Edit", new { id = Model.FlavorsId })</p><br>
<p>@Html.ActionLink("Delete Flavor", "Delete", new { id = Model.FlavorsId })</p><br>

PierreAuthId/Views/Flavors/Edit.cshtml
@{
  Layout = "_Layout";
}

@model PierreAuthId.Models.Flavors

<h2>Edit</h2>

<h4>Edit this Flavor: @Html.DisplayFor(model => model.Type)</h4>

@using (Html.BeginForm())
{
  @Html.HiddenFor(model => model.FlavorsId)

  @Html.LabelFor(model => model.Type)
  @Html.EditorFor(model => model.Type)

  <input type="submit" value="Save" />
}
<br>
<p>@Html.ActionLink("Back to list", "Index")</p>

PierreAuthId/Views/Flavors/Index.cshtml
@{
  Layout = "_Layout";
}

@using PierreAuthId.Models;

<h1>Flavors</h1>

@if (@Model.Count == 0)
{
  <h3>No flavors have been added yet!</h3>
} 

<ul>
  @foreach(Flavors Flavors in Model)
  {
    <li>@Html.ActionLink($"{Flavors.Type}", "Details", new { id = Flavors.FlavorsId })</li>
  }
</ul>

<p>@Html.ActionLink("Add new Flavors", "Create")</p>
<p>@Html.ActionLink("Home", "Index", "Home")</p>